--- 
- hosts: 172.31.81.14
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: I want to install apache2 server
    apt:
     name: apache2
     state: present

  - name: I want to copy the index file into ansible node
    template:
       src: myindex.j2
       dest: /var/www/html/index.html   