---
- hosts: mywebservers
  become: yes
  tasks:

  - name: I want to install a webserver
    apt:
     name: "{{mywebpackagesforubuntu}}"
     state: present
    when: ansible_os_family == "Debian"

  - name: I want to start the webserver
    service:
     name: "{{mywebpackagesforubuntu}}"
     state: started
    when: ansible_os_family == "Debian"

  - name: I want to install webserver Redhat node
    yum:
     name: "{{mywebpackagesforredhat}}"
     state: present
    when: ansible_os_family == "RedHat"


  - name: I want to start the Redhat server
    service:
     name: "{{mywebpackagesforredhat}}"
     state: started
    when: ansible_os_family == "RedHat"    